# Gateway Configuration:
server:
  port: ${SERVER_PORT}

# Gateway Routes:
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*' #Deberia ser el dominio del front
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - Content-Type
              - Authorization
      routes:
        - id: Auth-[auth,logIn,register,password]
          uri: ${AUTH_MS_URI}
          predicates:
            - Path=/v1/auth/**
            


