# Gateway Configuration:
server:
  port: ${SERVER_PORT}

# Gateway Routes:
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*' #Deberia ser el dominio del front
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - '*'
            allowCredentials: true
      routes:
        - id: Auth-[auth,logIn,register,password]
          uri: ${AUTH_MS_URI}
          predicates:
            - Path=/v1/auth/**
            


